OS-8
YevheniiH/organic-store pull request #2
Opened 2023-12-22 11:00 UTC by YevheniiH

2023-12-26 18:45 UTC, AndriiBatoh requested changes

2023-12-26 18:45 UTC, AndriiBatoh commented on src/app/design/frontend/Hanzha/OrganicStore/Magento_Customer/templates/account/customer.phtml
> +    <li class="customer-welcome test">
Do you still need this class here?

2023-12-26 20:16 UTC, YevheniiH commented on src/app/design/frontend/Hanzha/OrganicStore/Magento_Customer/templates/account/customer.phtml
> +    <li class="customer-welcome test">
Sorry! Thanks, removed!

2023-12-29 08:01 UTC, AndriiBatoh approved these changes

2023-12-29 08:01 UTC, merged